import {test} from 'node:test';import assert from 'node:assert/strict';import {chunkSegments} from '../src/retrieval.js';import {parseVtt,youtubeId} from '../src/captions.js';import {provider} from '../src/provider.js';
test('segments chunk once with source times',()=>{const segments=[{text:'a '.repeat(300),start:3,end:9},{text:'b '.repeat(140),start:10,end:17},{text:'c '.repeat(40),start:18,end:20}];const chunks=chunkSegments(segments);assert.equal(chunks.length,2);assert.equal(chunks[0].start,3);assert.equal(chunks[0].end,17);assert.equal(chunks[1].end,20)});
test('caption parsing keeps timestamps',()=>{const x=parseVtt('WEBVTT\n\n00:00:01.000 --> 00:00:02.000\nHello\n\n00:00:03.000 --> 00:00:05.000\nworld');assert.equal(x.length,2);assert.deepEqual(x.map(c=>c.start),[1,3])});
test('YouTube URL rejects wrong host and malformed id',()=>{assert.throws(()=>youtubeId('https://evil.example/watch?v=abcdefghijk'));assert.equal(youtubeId('https://www.youtube.com/watch?v=abcdefghijk'),'abcdefghijk')});
test('mock embedding deterministic 1536 dimensions',async()=>{const p=provider();const a=await p.embed('cells make proteins');const b=await p.embed('cells make proteins');assert.equal(a.length,1536);assert.deepEqual(a,b)});
test('mock MCQs cite a source chunk',async()=>{const p=provider();const chunks=[{id:'chunk-a',text:'Nucleus stores DNA in the cell',start_ts:12,end_ts:18}];const questions=await p.generate('mcq',chunks);assert.equal(questions[0].source_chunk_id,'chunk-a');assert.equal(await p.verifyMcq(questions[0],chunks),true)});
test('auth rejects missing token before database access',async()=>{const app=(await import('../src/app.js')).default;const request=(await import('supertest')).default;const response=await request(app).get('/notebooks');assert.equal(response.status,401)});
test('health responds without infrastructure',async()=>{const app=(await import('../src/app.js')).default;const request=(await import('supertest')).default;const response=await request(app).get('/health');assert.equal(response.status,200);assert.equal(response.body.ok,true)});
test('Gemini adapter generation/embedding with stubbed HTTP response',async()=>{const previous={provider:process.env.AI_PROVIDER,key:process.env.GEMINI_API_KEY,fetch:global.fetch};process.env.AI_PROVIDER='gemini';process.env.GEMINI_API_KEY='test-key-not-real';global.fetch=async(url)=>({ok:true,json:async()=>String(url).includes('embedContent')?{embedding:{values:Array(1536).fill(.5)}}:{candidates:[{content:{parts:[{text:JSON.stringify({items:[{heading:'Test',bullets:[{text:'One cited claim',source_chunk_id:'source-1'}]}]})}]}}]}});try{const {provider}=await import('../src/provider.js');const p=provider();assert.equal((await p.embed('cell')).length,1536);const notes=await p.generate('summary',[{id:'source-1',text:'Cells',start_ts:0,end_ts:10}]);assert.equal(notes[0].bullets[0].source_chunk_id,'source-1')}finally{global.fetch=previous.fetch;process.env.AI_PROVIDER=previous.provider??'mock';if(previous.key)process.env.GEMINI_API_KEY=previous.key;else delete process.env.GEMINI_API_KEY}});
test('video duration rejects model timestamps beyond the actual public video',async()=>{const {validateTimedSegments}=await import('../src/retrieval.js');assert.throws(()=>validateTimedSegments([{text:'x',start:10,end:242}],180),/exceeds verified video duration/);assert.deepEqual(validateTimedSegments([{text:'x',start:10,end:180}],180),[{text:'x',start:10,end:180}])});

test('unknown duration preserves but does not verify ordered times',async()=>{const {validateTimedSegments}=await import('../src/retrieval.js');assert.deepEqual(validateTimedSegments([{text:'x',start:10,end:242}],null),[{text:'x',start:10,end:242}]);assert.throws(()=>validateTimedSegments([{text:'a',start:0,end:10},{text:'b',start:9,end:20}],null),/overlapping/)});
test('OpenRouter extracts fenced JSON and falls back on 429',async()=>{const prev={key:process.env.OPENROUTER_API_KEY,fetch:global.fetch};process.env.OPENROUTER_API_KEY='test-not-real';let calls=[];global.fetch=async(_url,opts)=>{const model=JSON.parse(opts.body).model;calls.push(model);if(model!=='openrouter/free')return {ok:false,status:429,text:async()=>'{"error":"rate limited"}',headers:{get:()=>null}};return {ok:true,json:async()=>({choices:[{message:{content:'```json\nHere is JSON: {"items":[{"heading":"Hi","bullets":[]}]}\n```'}}]})}};try{const {openrouterJson}=await import('../src/openrouter.js');const result=await openrouterJson('JSON only','hello');assert.equal(result.items[0].heading,'Hi');assert.deepEqual(calls,['google/gemma-4-31b-it:free','google/gemma-4-31b-it:free','openrouter/free'])}finally{global.fetch=prev.fetch;if(prev.key)process.env.OPENROUTER_API_KEY=prev.key;else delete process.env.OPENROUTER_API_KEY}});
