import 'dotenv/config';import express from 'express';import helmet from 'helmet';import multer from 'multer';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';import {randomUUID} from 'node:crypto';import {z} from 'zod';import PDFDocument from 'pdfkit';import sanitizeHtml from 'sanitize-html';import {query} from './db.js';import {jobQueue,redis} from './queue.js';import {retrieve,retrieveNotebook} from './retrieval.js';import {provider} from './provider.js';import {store,maxUploadMb} from './storage.js';import {youtubeId,parseVtt} from './captions.js';import {authRateLimit} from './rate-limit.js';import {extractiveMoments} from './extractive.js';
const app=express();app.set('trust proxy',1);app.use(helmet());app.use(express.json({limit:'1mb'}));app.use((req,res,next)=>{const origin=process.env.CORS_ORIGIN??'http://localhost:3000';res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Authorization,Content-Type');res.setHeader('Access-Control-Allow-Methods','GET,POST,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next()});const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:maxUploadMb()*1024*1024},fileFilter:(req,file,cb)=>{if(!file.mimetype.startsWith('video/'))return cb(new Error('A video file is required'));cb(null,true)}});const captionUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024}});const types=new Set(['summary','notes','exam_notes','mcq']);
const wrap=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);function parse(schema,input){const result=schema.safeParse(input);if(!result.success){const e=new Error(result.error.issues.map(x=>x.message).join('; '));e.status=400;throw e}return result.data}
const token=user=>jwt.sign({sub:user.id,email:user.email},process.env.JWT_SECRET,{expiresIn:'7d'});const auth=wrap(async(req,res,next)=>{const raw=req.get('Authorization')?.match(/^Bearer (.+)$/)?.[1];if(!raw)return res.status(401).json({error:'Authentication required'});try{const data=jwt.verify(raw,process.env.JWT_SECRET);req.user={id:data.sub,email:data.email};next()}catch{return res.status(401).json({error:'Invalid or expired token'})}});
const owner=wrap(async(req,res,next)=>{const {rows:[v]}=await query(`SELECT v.* FROM videos v JOIN notebooks n ON n.id=v.notebook_id WHERE v.id=$1 AND n.user_id=$2`,[req.params.id,req.user.id]);if(!v)return res.status(404).json({error:'Video not found'});req.video=v;next()});const notebookOwner=wrap(async(req,res,next)=>{const {rows:[n]}=await query('SELECT * FROM notebooks WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);if(!n)return res.status(404).json({error:'Notebook not found'});req.notebook=n;next()});
app.get('/health',(req,res)=>res.json({ok:true,provider:process.env.AI_PROVIDER??'mock'}));
app.post('/auth/signup',authRateLimit({kind:'signup',perIp:20,perEmail:5}),wrap(async(req,res)=>{const {email,password}=parse(z.object({email:z.email().max(254),password:z.string().min(8).max(100)}),req.body);const hash=await bcrypt.hash(password,12);try{const {rows:[u]}=await query('INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING id,email',[email.toLowerCase(),hash]);res.status(201).json({user:u,token:token(u)})}catch(e){if(e.code==='23505')return res.status(409).json({error:'Email already in use'});throw e}}));
app.post('/auth/login',authRateLimit({kind:'login',perIp:60,perEmail:10}),wrap(async(req,res)=>{const {email,password}=parse(z.object({email:z.email(),password:z.string()}),req.body);const {rows:[u]}=await query('SELECT * FROM users WHERE email=$1',[email.toLowerCase()]);if(!u||!await bcrypt.compare(password,u.password_hash))return res.status(401).json({error:'Invalid credentials'});res.json({user:{id:u.id,email:u.email},token:token(u)})}));
app.get('/notebooks',auth,wrap(async(req,res)=>{const {rows}=await query(`SELECT n.*,count(v.id)::int AS video_count,max(v.updated_at) AS updated_at FROM notebooks n LEFT JOIN videos v ON v.notebook_id=n.id WHERE n.user_id=$1 GROUP BY n.id ORDER BY n.created_at DESC`,[req.user.id]);res.json({notebooks:rows})}));
app.post('/notebooks',auth,wrap(async(req,res)=>{const {title}=parse(z.object({title:z.string().trim().min(1).max(120)}),req.body);const {rows:[n]}=await query('INSERT INTO notebooks(user_id,title) VALUES($1,$2) RETURNING *',[req.user.id,title]);res.status(201).json({notebook:n})}));
app.get('/notebooks/:id/videos',auth,notebookOwner,wrap(async(req,res)=>{const {rows}=await query(`SELECT v.id,v.title,v.status,v.duration,v.timestamps_verified,v.source_type,v.source_url,v.error,v.created_at,v.updated_at,(SELECT count(*)::int FROM artifacts a WHERE a.video_id=v.id) AS artifact_count,(SELECT EXISTS(SELECT 1 FROM transcripts t WHERE t.video_id=v.id)) AS has_transcript,(SELECT EXISTS(SELECT 1 FROM chunks c WHERE c.video_id=v.id)) AS has_chunks FROM videos v WHERE v.notebook_id=$1 ORDER BY v.created_at DESC`,[req.notebook.id]);res.json({videos:rows.map(v=>({...v,progress:processingProgress(v.status,v.artifact_count,v.has_transcript,v.has_chunks)}))})}));
app.get('/notebooks/:id/search',auth,notebookOwner,wrap(async(req,res)=>{const {q}=parse(z.object({q:z.string().trim().min(1).max(500)}),req.query);res.json({results:await retrieveNotebook(req.notebook.id,req.user.id,q)})}));
app.post('/videos',auth,upload.single('file'),wrap(async(req,res)=>{const {notebook_id,title,youtube_url}=parse(z.object({notebook_id:z.uuid(),title:z.string().trim().min(1).max(200).optional(),youtube_url:z.url().optional()}),req.body);const {rows:[notebook]}=await query('SELECT id FROM notebooks WHERE id=$1 AND user_id=$2',[notebook_id,req.user.id]);if(!notebook)return res.status(404).json({error:'Notebook not found'});if(Boolean(req.file)===Boolean(youtube_url))return res.status(400).json({error:'Provide exactly one video file or YouTube URL'});if(youtube_url)youtubeId(youtube_url);if(req.file&&!req.file.mimetype.startsWith('video/'))return res.status(400).json({error:'A video file is required'});const id=randomUUID(),source_type=req.file?'upload':'youtube',storage_key=req.file?`${req.user.id}/${id}/${req.file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_')}`:null;if(req.file)await store(storage_key,req.file.buffer,req.file.mimetype);const {rows:[v]}=await query('INSERT INTO videos(id,notebook_id,title,source_type,source_url,storage_key) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,title,status,source_type',[id,notebook_id,title??req.file?.originalname??'YouTube lesson',source_type,youtube_url??null,storage_key]);try{await jobQueue().add('process',{videoId:id},{jobId:`process-${id}`})}catch(e){await query('UPDATE videos SET status=$2,error=$3 WHERE id=$1',[id,'failed','Queue unavailable']);throw e}res.status(202).json({video:v})}));
app.get('/videos/:id/extractive-summary',auth,owner,wrap(async(req,res)=>{const {rows:chunks}=await query('SELECT id,text,start_ts,end_ts FROM chunks WHERE video_id=$1 ORDER BY start_ts',[req.video.id]);if(!chunks.length)return res.status(404).json({error:'Indexed transcript not ready'});const content=extractiveMoments(chunks);res.json({extractive:{content,covered_chunks:chunks.length,total_chunks:chunks.length,method:'source_excerpts',note:'Exact selected transcript excerpts across the timeline, not a generated full summary.'},sources:Object.fromEntries(chunks.map(c=>[c.id,{start_ts:c.start_ts,end_ts:c.end_ts}]))})}));
app.get('/videos/:id/preliminary-summary',auth,owner,wrap(async(req,res)=>{const {rows:[preview]}=await query('SELECT content,covered_chunks,total_chunks,created_at FROM preliminary_summaries WHERE video_id=$1',[req.video.id]);if(!preview)return res.status(404).json({error:'Preliminary summary not ready'});const {rows:chunks}=await query('SELECT id,start_ts,end_ts FROM chunks WHERE video_id=$1 ORDER BY start_ts LIMIT 8',[req.video.id]);res.json({preliminary:preview,sources:Object.fromEntries(chunks.map(c=>[c.id,{start_ts:c.start_ts,end_ts:c.end_ts}]))})}));
app.get('/videos/:id/summary-edit',auth,owner,wrap(async(req,res)=>{const {rows:[edit]}=await query('SELECT content,updated_at FROM summary_edits WHERE video_id=$1 AND user_id=$2',[req.video.id,req.user.id]);res.json({edit:edit??null})}));
app.put('/videos/:id/summary-edit',auth,owner,wrap(async(req,res)=>{const {content:incoming}=parse(z.object({content:z.string().max(50000)}),req.body);const content=sanitizeHtml(incoming,{allowedTags:['p','br','strong','em','u','mark','h2','ul','ol','li'],allowedAttributes:{}});const {rows:[edit]}=await query(`INSERT INTO summary_edits(video_id,user_id,content) VALUES($1,$2,$3) ON CONFLICT(video_id,user_id) DO UPDATE SET content=EXCLUDED.content,updated_at=now() RETURNING content,updated_at`,[req.video.id,req.user.id,content]);res.json({edit})}));
app.get('/videos/:id/notes',auth,owner,wrap(async(req,res)=>{const {rows}=await query('SELECT id,text,source_chunk_id,created_at,updated_at FROM user_notes WHERE video_id=$1 AND user_id=$2 ORDER BY created_at',[req.video.id,req.user.id]);res.json({notes:rows})}));
app.post('/videos/:id/notes',auth,owner,wrap(async(req,res)=>{const {text,source_chunk_id}=parse(z.object({text:z.string().trim().min(1).max(10000),source_chunk_id:z.uuid().nullable().optional()}),req.body);if(source_chunk_id){const {rows}=await query('SELECT 1 FROM chunks WHERE id=$1 AND video_id=$2',[source_chunk_id,req.video.id]);if(!rows.length)return res.status(400).json({error:'Source chunk is not in this video'})}const {rows:[note]}=await query('INSERT INTO user_notes(video_id,user_id,text,source_chunk_id) VALUES($1,$2,$3,$4) RETURNING *',[req.video.id,req.user.id,text,source_chunk_id??null]);res.status(201).json({note})}));
app.patch('/videos/:id/notes/:noteId',auth,owner,wrap(async(req,res)=>{const {text}=parse(z.object({text:z.string().trim().min(1).max(10000)}),req.body);const {rows:[note]}=await query('UPDATE user_notes SET text=$4,updated_at=now() WHERE id=$1 AND video_id=$2 AND user_id=$3 RETURNING *',[req.params.noteId,req.video.id,req.user.id,text]);if(!note)return res.status(404).json({error:'Note not found'});res.json({note})}));
app.delete('/videos/:id/notes/:noteId',auth,owner,wrap(async(req,res)=>{const {rowCount}=await query('DELETE FROM user_notes WHERE id=$1 AND video_id=$2 AND user_id=$3',[req.params.noteId,req.video.id,req.user.id]);if(!rowCount)return res.status(404).json({error:'Note not found'});res.sendStatus(204)}));
app.post('/videos/:id/captions',auth,owner,captionUpload.single('captions'),wrap(async(req,res)=>{
 if(req.video.source_type!=='youtube')return res.status(400).json({error:'Caption upload requires a YouTube video'});
 if(req.video.status!=='failed')return res.status(409).json({error:'Wait for processing to fail before replacing captions'});
 const file=req.file;if(!file||file.size>5*1024*1024||!/(\.vtt|\.srt|\.txt)$/i.test(file.originalname))return res.status(400).json({error:'Upload timed captions as .vtt, .srt or .txt under 5 MB'});
 const raw=file.buffer.toString('utf8');if(/\.txt$/i.test(file.originalname)&&!(/(?:^|\n)WEBVTT\b/i.test(raw)||/\d{1,2}:\d{2}:\d{2}[.,]\d{3}\s*-->\s*\d{1,2}:\d{2}:\d{2}[.,]\d{3}/.test(raw)))return res.status(400).json({error:'The .txt file must contain WEBVTT or SRT timed captions'});const cues=parseVtt(raw);if(!cues.length)return res.status(400).json({error:'No timed captions found in file'});
 if(cues.length>20000)return res.status(400).json({error:'Too many caption cues'});let prior=-1;for(const c of cues){if(!Number.isFinite(c.start)||!Number.isFinite(c.end)||c.start<0||c.end<c.start||c.start<prior||c.end>43200)return res.status(400).json({error:'Caption timestamps are invalid'});prior=c.start}
 await query('INSERT INTO video_caption_uploads(video_id,raw_vtt) VALUES($1,$2) ON CONFLICT(video_id) DO UPDATE SET raw_vtt=EXCLUDED.raw_vtt,created_at=now()',[req.video.id,raw]);
 await query('UPDATE videos SET status=$2,error=NULL,updated_at=now() WHERE id=$1',[req.video.id,'transcribing']);
 try{const job=await jobQueue().add('process',{videoId:req.video.id},{jobId:`captions-${req.video.id}-${Date.now()}`});res.status(202).json({job_id:job.id,status:'transcribing',cue_count:cues.length})}catch(e){await query('UPDATE videos SET status=$2,error=$3 WHERE id=$1',[req.video.id,'failed','Caption queue unavailable']);throw e}
}));
app.post('/videos/:id/resume',auth,owner,wrap(async(req,res)=>{if(req.video.status!=='failed')return res.status(409).json({error:'Video is not failed'});const {rows:chunks}=await query('SELECT id FROM chunks WHERE video_id=$1 LIMIT 1',[req.video.id]);if(!chunks.length)return res.status(409).json({error:'No saved transcript chunks to resume'});await query('UPDATE videos SET status=$2,error=NULL,updated_at=now() WHERE id=$1',[req.video.id,'generating']);try{const job=await jobQueue().add('process',{videoId:req.video.id},{jobId:`resume-${req.video.id}-${Date.now()}`});res.status(202).json({job_id:job.id,status:'generating'})}catch(e){await query('UPDATE videos SET status=$2,error=$3 WHERE id=$1',[req.video.id,'failed','Resume queue unavailable']);throw e}}));
export function processingProgress(status,artifactCount=0,hasTranscript=false,hasChunks=false){
 // Persisted milestones, not time spent: transcript, indexed chunks, four artifacts.
 const complete=Math.min(6,Number(Boolean(hasTranscript))+Number(Boolean(hasChunks))+Math.max(0,Math.min(4,Number(artifactCount)||0)));
 return {percent:Math.floor(complete/6*100),completed:complete,total:6};
}
app.get('/videos/:id/status',auth,owner,wrap(async(req,res)=>{const {rows:[counts]}=await query(`SELECT (SELECT count(*)::int FROM artifacts WHERE video_id=$1) AS artifact_count,(SELECT EXISTS(SELECT 1 FROM transcripts WHERE video_id=$1)) AS has_transcript,(SELECT EXISTS(SELECT 1 FROM chunks WHERE video_id=$1)) AS has_chunks`,[req.video.id]);res.json({video_id:req.video.id,status:req.video.status,error:req.video.error,timestamps_verified:req.video.timestamps_verified,updated_at:req.video.updated_at,progress:processingProgress(req.video.status,counts?.artifact_count,counts?.has_transcript,counts?.has_chunks)})}));
app.get('/videos/:id/events',auth,owner,wrap(async(req,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache, no-transform');res.setHeader('Connection','keep-alive');res.flushHeaders();res.write(`event: status\ndata: ${JSON.stringify({video_id:req.video.id,status:req.video.status})}\n\n`);const subscriber=redis().duplicate();subscriber.on('error',()=>{});await subscriber.subscribe(`video:${req.video.id}`);const handler=(channel,message)=>{res.write(`event: status\ndata: ${message}\n\n`)};subscriber.on('message',handler);const heartbeat=setInterval(()=>res.write(': ping\n\n'),20000);req.on('close',()=>{clearInterval(heartbeat);subscriber.off('message',handler);subscriber.quit().catch(()=>{})})}));
app.get('/videos/:id/artifacts/:type',auth,owner,wrap(async(req,res)=>{if(!types.has(req.params.type))return res.status(400).json({error:'Unknown artifact type'});const {rows:[a]}=await query('SELECT * FROM artifacts WHERE video_id=$1 AND type=$2',[req.video.id,req.params.type]);if(!a)return res.status(404).json({error:'Artifact not ready'});const {rows:chunks}=await query('SELECT id,start_ts,end_ts FROM chunks WHERE video_id=$1',[req.video.id]);res.json({artifact:a,sources:Object.fromEntries(chunks.map(c=>[c.id,{start_ts:c.start_ts,end_ts:c.end_ts}]))})}));
app.post('/videos/:id/artifacts/:type/regenerate',auth,owner,wrap(async(req,res)=>{if(!types.has(req.params.type))return res.status(400).json({error:'Unknown artifact type'});if(req.video.status!=='ready')return res.status(409).json({error:'Video is not ready'});const job=await jobQueue().add('regenerate',{videoId:req.video.id,type:req.params.type});res.status(202).json({job_id:job.id,status:'queued'})}));
app.get('/videos/:id/search',auth,owner,wrap(async(req,res)=>{const {q}=parse(z.object({q:z.string().trim().min(1).max(500)}),req.query);res.json({results:await retrieve(req.video.id,q)})}));
app.post('/videos/:id/explain',auth,owner,wrap(async(req,res)=>{const {chunk_id,question}=parse(z.object({chunk_id:z.uuid(),question:z.string().max(500).optional()}),req.body);const {rows:[chunk]}=await query('SELECT id,text,start_ts,end_ts FROM chunks WHERE id=$1 AND video_id=$2',[chunk_id,req.video.id]);if(!chunk)return res.status(404).json({error:'Source chunk not found'});const matches=await retrieve(req.video.id,question??chunk.text.slice(0,300),3);const answer=await provider().reply(question??'Explain this note in more depth',matches,{explain:true});res.json({answer,citations:matches.map(x=>({chunk_id:x.id,start_ts:x.start_ts,end_ts:x.end_ts}))})}));
app.post('/videos/:id/tutor/chat',auth,owner,wrap(async(req,res)=>{const {message}=parse(z.object({message:z.string().trim().min(1).max(2000)}),req.body);const {rows:history}=await query('SELECT role,content FROM chat_messages WHERE video_id=$1 AND user_id=$2 ORDER BY created_at DESC LIMIT 10',[req.video.id,req.user.id]);const chunks=await retrieve(req.video.id,message+' '+history.slice(0,3).map(x=>x.content).join(' '),5);const strong=chunks.filter(c=>Number(c.similarity)>=0.22);const general=!strong.length;const answer=await provider().reply(message,general?[]:strong,{general,history:history.reverse()});const citations=general?[]:strong.map(c=>({chunk_id:c.id,start_ts:c.start_ts,end_ts:c.end_ts,similarity:c.similarity}));await query('INSERT INTO chat_messages(video_id,user_id,role,content) VALUES($1,$2,$3,$4)',[req.video.id,req.user.id,'user',message]);await query('INSERT INTO chat_messages(video_id,user_id,role,content,cited_chunk_ids,general_knowledge) VALUES($1,$2,$3,$4,$5,$6)',[req.video.id,req.user.id,'assistant',answer,citations.map(c=>c.chunk_id),general]);res.json({answer,grounding:general?'general_knowledge':'grounded_in_video',citations})}));
app.get('/videos/:id/export',auth,owner,wrap(async(req,res)=>{const {type,format}=parse(z.object({type:z.enum(['summary','notes','exam_notes','mcq']),format:z.enum(['pdf','doc'])}),req.query);const {rows:[a]}=await query('SELECT content FROM artifacts WHERE video_id=$1 AND type=$2',[req.video.id,type]);if(!a)return res.status(404).json({error:'Artifact not ready'});if(format==='doc'){res.type('application/msword');res.setHeader('Content-Disposition',`attachment; filename="${type}.doc"`);const escaped=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));return res.send(`<html><meta charset="utf-8"><body><h1>${escaped(req.video.title)} - ${type}</h1>${a.content.map(item=>`<h2>${escaped(item.heading??item.question)}</h2><p>${escaped(item.bullets?.map(b=>b.text).join('; ')??item.explanation??'')}</p>`).join('')}</body></html>`)}const doc=new PDFDocument();res.type('application/pdf');res.setHeader('Content-Disposition',`attachment; filename="${type}.pdf"`);doc.pipe(res);doc.fontSize(18).text(`${req.video.title} - ${type}`);for(const item of a.content){doc.moveDown().fontSize(13).text(item.heading??item.question);doc.fontSize(10).text(item.bullets?.map(b=>b.text).join('\n')??item.explanation??'')}doc.end()}));
app.use((err,req,res,next)=>{console.error(err);if(res.headersSent)return next(err);res.status(err.status??(err instanceof multer.MulterError?400:500)).json({error:err.status||err instanceof multer.MulterError?(err.code==='LIMIT_FILE_SIZE'?`Video upload exceeds ${maxUploadMb()}MB limit`:err.message):'Internal server error'})});export default app;
