export type Notebook = {id:string; title:string; subject:string; updated:string; videos:number; color:string};
export const initialNotebooks:Notebook[] = [
{id:'biology',title:'Biology foundations',subject:'Biology',updated:'Updated today',videos:4,color:'mint'},
{id:'physics',title:'Physics essentials',subject:'Physics',updated:'Updated yesterday',videos:3,color:'lilac'},
{id:'history',title:'World history',subject:'History',updated:'Updated Sep 22',videos:2,color:'peach'}];
export type Video = {id:string; title:string; source:string; duration:string; status:'Ready'|'Transcribing'|'Chunking'|'Generating notes'; updated:string};
export const videos:Video[] = [
{id:'cell-biology',title:'The cell: Structure and function',source:'Video lesson',duration:'18:42',status:'Ready',updated:'Today at 10:24'},
{id:'photosynthesis',title:'Photosynthesis, explained simply',source:'Video lesson',duration:'24:15',status:'Ready',updated:'Yesterday'},
{id:'genetics',title:'How genes become traits',source:'Video lesson',duration:'32:08',status:'Generating notes',updated:'Just added'},
{id:'mitosis',title:'Mitosis in five stages',source:'Video lesson',duration:'15:36',status:'Transcribing',updated:'Just added'}];
export const transcript=[{time:'00:48',text:'Cells are the smallest living units and form the building blocks of every organism.'},{time:'02:14',text:'The cell membrane controls which substances enter and leave the cell.'},{time:'04:36',text:'The nucleus stores DNA and coordinates cell activity.'},{time:'07:21',text:'Mitochondria convert nutrients into usable energy through cellular respiration.'},{time:'11:09',text:'Ribosomes build proteins based on instructions from RNA.'},{time:'15:32',text:'Plant cells contain chloroplasts and a rigid cell wall.'}];
export const summaries=[{id:'s1',time:'00:48',heading:'The big picture',text:'Cells are the basic units of life. Every organism is made of one or more cells, each with a set of specialized parts.'},{id:'s2',time:'02:14',heading:'What protects the cell',text:'The cell membrane acts as a selective boundary, controlling what enters and leaves the cell.'},{id:'s3',time:'04:36',heading:'The control center',text:'The nucleus holds DNA and directs many of the cell’s activities.'},{id:'s4',time:'07:21',heading:'How cells get energy',text:'Mitochondria turn nutrients into usable energy so the cell can do its work.'}];
export const notes=[{id:'n1',time:'00:48',heading:'Cell theory',text:'All living things are made of cells. Cells are the smallest units that can carry out life processes.'},{id:'n2',time:'02:14',heading:'Cell membrane',text:'A selectively permeable outer layer that regulates the movement of materials in and out.'},{id:'n3',time:'04:36',heading:'Nucleus',text:'Contains genetic material (DNA) and coordinates growth, metabolism, and reproduction.'},{id:'n4',time:'07:21',heading:'Mitochondria',text:'Sites of cellular respiration, producing ATP from nutrients.'},{id:'n5',time:'11:09',heading:'Ribosomes',text:'Small structures responsible for protein synthesis.'}];
export const examNotes=[{id:'e1',time:'00:48',heading:'Define a cell',text:'The basic structural and functional unit of life. Key phrase: all organisms consist of one or more cells.'},{id:'e2',time:'02:14',heading:'Compare membrane and wall',text:'The membrane controls transport in all cells; the wall provides rigid support in plant cells.'},{id:'e3',time:'04:36',heading:'Nucleus vs. mitochondrion',text:'The nucleus stores DNA and controls cell activity. Mitochondria produce ATP through respiration.'},{id:'e4',time:'15:32',heading:'Likely exam question',text:'Name two structures found in plant cells but not animal cells: chloroplasts and a cell wall.'}];
export const questions=[{id:'q1',question:'What is the primary role of the cell membrane?',options:['To store genetic material','To control what enters and leaves the cell','To produce proteins','To convert sunlight into energy'],answer:1,explanation:'The cell membrane is selectively permeable, regulating the movement of materials in and out.',time:'02:14'},{id:'q2',question:'Which organelle stores the cell’s DNA?',options:['Ribosome','Mitochondrion','Nucleus','Cell membrane'],answer:2,explanation:'The nucleus contains DNA and coordinates many cell activities.',time:'04:36'},{id:'q3',question:'What do mitochondria produce for the cell?',options:['ATP (usable energy)','DNA','Cell walls','Proteins'],answer:0,explanation:'Mitochondria use cellular respiration to produce ATP.',time:'07:21'}];
